name: build mold

on: workflow_dispatch

jobs:

  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: clang32
          update: true
          install: >-
            binutils
            mingw-w64-clang-i686-cmake
            mingw-w64-clang-i686-ninja

      - name: build CodeBlocks
        shell: msys2 {0}
        id: build
        run: |
          cd mingw-w64-mold
          MINGW_ARCH=clang32 makepkg-mingw -sLf
          pacman -U mingw-w64-mold*.pkg.tar.xz
