name: build CodeBlocks

on: workflow_dispatch

jobs:

  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw32

      - name: build CodeBlocks
        shell: msys2 {0}
        id: buildcb
        run: |
          pacman -S --noconfirm mingw-w64-i686-toolchain
          cd mingw-w64-codeblocks
          MINGW_ARCH=mingw32 makepkg-mingw -sLf
          pacman -U mingw-w64-codeblocks*.pkg.tar.xz
